### ISSUE TITLE
Create GenerateRandomFileName in Utilities

### ISSUE THREAD

**Issue by jlechem** [jlechem/RetroGaming#3]
We need a way to generate a random (GUID) filename. We should add a function in the utilities class that returns a new random GUID.txt filename. Where GUID is an actual new guid. We could also add an optional parameter as the extension and if no extension is specified just assume .txt

for example 5d4f5989-ece0-4adc-a8e6-4389c0b688d9.txt

**Comment by jlechem** [comment]
A UUID generation library has been added to the solution but hasn't been implemented yet. There are some naming collisions going on that need to be resolved first.

**Comment by geekskick** [comment]
I'd like to have a look at this if thats ok?

Would you please provide a .clang-format so I can make sure that my stuff matches your stuff? Thanks

**Comment by jlechem** [comment]
Of course!

**Comment by jlechem** [comment]
I've been using Visual Studio so I'll have to setup a clang version to test.

**Comment by geekskick** [comment]
I am on a Mac and don’t have visual studio. I have got it building using a makefile. It looks like nmake will build a VS configuration from the makefile, and I would imagine that there is some kind of CMake integration for VS. What would you prefer for a xplatform build system?

**Comment by jlechem** [comment]
Code implemented and looks great.
